channels:
    - conda-forge
    - conda-forge/label/prerelease-jupyterlab
dependencies:
#    - nbgitpuller
    - pip
##################################
  - xeus-cling=0.12.1
  - xtensor=0.23.0
  - xtensor-blas=0.19.0
  - boost
  - eigen
##################################
    - pip: 
        - numpy
        - pycrypto
#         - TA-Lib
