channels:
    - conda-forge
    - conda-forge/label/prerelease-jupyterlab
dependencies:
    - nbgitpuller
    - pip
    - pip: 
        - nbdime
        - jupyterlab-git
        - numpy
        - pycrypto
#         - TA-Lib
